const PDFDocument = require('pdfkit');
const fs = require('fs');
const path = require('path');

async function testPDFGeneration() {
    try {
        console.log('Testing PDF generation...');
        
        // Crear directorio si no existe
        const reportsDir = './reports';
        if (!fs.existsSync(reportsDir)) {
            fs.mkdirSync(reportsDir, { recursive: true });
            console.log('Reports directory created');
        }

        const filePath = path.join(reportsDir, 'test-pdf.pdf');
        
        // Crear PDF simple
        const doc = new PDFDocument();
        const stream = fs.createWriteStream(filePath);
        doc.pipe(stream);

        // Agregar contenido básico
        doc.fontSize(20).text('Test PDF Document', 100, 100);
        doc.fontSize(14).text('This is a test PDF generated by DobackSoft', 100, 150);
        doc.text('If you can read this, PDF generation is working correctly.', 100, 200);

        doc.end();

        stream.on('finish', () => {
            const stats = fs.statSync(filePath);
            console.log('PDF generated successfully:');
            console.log('- File path:', filePath);
            console.log('- File size:', stats.size, 'bytes');
            console.log('- File exists:', fs.existsSync(filePath));
            
            // Verificar contenido
            const content = fs.readFileSync(filePath);
            console.log('- Content type:', typeof content);
            console.log('- Is PDF (starts with %PDF):', content.toString('ascii', 0, 4) === '%PDF');
        });

        stream.on('error', (error) => {
            console.error('Error creating PDF:', error);
        });

    } catch (error) {
        console.error('Test failed:', error);
    }
}

testPDFGeneration(); 