[mypy]
python_version = 3.10
warn_return_any = True
warn_unused_configs = True
disallow_untyped_defs = True
disallow_incomplete_defs = True
check_untyped_defs = True
disallow_untyped_decorators = True
no_implicit_optional = True
warn_redundant_casts = True
warn_unused_ignores = True
warn_no_return = True
warn_unreachable = True
strict_optional = True

[mypy.plugins.flask.*]
init_typed = True

[mypy.plugins.sqlalchemy.*]
init_typed = True

[mypy-flask_sqlalchemy.*]
ignore_missing_imports = True

[mypy-flask_migrate.*]
ignore_missing_imports = True

[mypy-flask_jwt_extended.*]
ignore_missing_imports = True

[mypy-flask_mail.*]
ignore_missing_imports = True

[mypy-flask_caching.*]
ignore_missing_imports = True

[mypy-flask_limiter.*]
ignore_missing_imports = True

[mypy-flask_cors.*]
ignore_missing_imports = True

[mypy-gunicorn.*]
ignore_missing_imports = True

[mypy-redis.*]
ignore_missing_imports = True

[mypy-boto3.*]
ignore_missing_imports = True

[mypy-botocore.*]
ignore_missing_imports = True

[mypy-psycopg2.*]
ignore_missing_imports = True 